plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/nickjsorenson/heretic-engine-revenue-physics-engine/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]